baseurl = "https://altairmn.github.io"
languageCode = "en-us"
title = "sahilmn"
theme = "hugo-classic"
googleAnalytics = ""
publishDir = "docs"
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
enableEmoji = true
enableGitInfo = true
footnotereturnlinkcontents = "↩"
staticDir=["static"]

[permalinks]
    post = "/post/:year/:month/:day/:slug/"
